/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminQuotaRouteImport } from './routes/admin-quota'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CheckoutReturnRouteImport } from './routes/checkout-return'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ShareRouteImport } from './routes/share'
import { Route as TrellisTestRouteImport } from './routes/trellis-test'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountDownloadsRouteImport } from './routes/account.downloads'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotaRoute = AdminQuotaRouteImport.update({
  id: '/admin-quota',
  path: '/admin-quota',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout-return',
  path: '/checkout-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const TrellisTestRoute = TrellisTestRouteImport.update({
  id: '/trellis-test',
  path: '/trellis-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDownloadsRoute = AccountDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/admin-quota': typeof AdminQuotaRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-return': typeof CheckoutReturnRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/help': typeof HelpRoute
  '/projects': typeof ProjectsRoute
  '/share': typeof ShareRoute
  '/trellis-test': typeof TrellisTestRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/': typeof AccountIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-quota': typeof AdminQuotaRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-return': typeof CheckoutReturnRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/help': typeof HelpRoute
  '/projects': typeof ProjectsRoute
  '/share': typeof ShareRoute
  '/trellis-test': typeof TrellisTestRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account': typeof AccountIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/admin-quota': typeof AdminQuotaRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-return': typeof CheckoutReturnRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/help': typeof HelpRoute
  '/projects': typeof ProjectsRoute
  '/share': typeof ShareRoute
  '/trellis-test': typeof TrellisTestRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/': typeof AccountIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/admin-quota'
    | '/auth'
    | '/checkout'
    | '/checkout-return'
    | '/contact'
    | '/dashboard'
    | '/editor'
    | '/help'
    | '/projects'
    | '/share'
    | '/trellis-test'
    | '/account/downloads'
    | '/account/orders'
    | '/account/settings'
    | '/account/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-quota'
    | '/auth'
    | '/checkout'
    | '/checkout-return'
    | '/contact'
    | '/dashboard'
    | '/editor'
    | '/help'
    | '/projects'
    | '/share'
    | '/trellis-test'
    | '/account/downloads'
    | '/account/orders'
    | '/account/settings'
    | '/account'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/admin-quota'
    | '/auth'
    | '/checkout'
    | '/checkout-return'
    | '/contact'
    | '/dashboard'
    | '/editor'
    | '/help'
    | '/projects'
    | '/share'
    | '/trellis-test'
    | '/account/downloads'
    | '/account/orders'
    | '/account/settings'
    | '/account/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRoute
  AdminQuotaRoute: typeof AdminQuotaRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  HelpRoute: typeof HelpRoute
  ProjectsRoute: typeof ProjectsRoute
  ShareRoute: typeof ShareRoute
  TrellisTestRoute: typeof TrellisTestRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-quota': {
      id: '/admin-quota'
      path: '/admin-quota'
      fullPath: '/admin-quota'
      preLoaderRoute: typeof AdminQuotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-return': {
      id: '/checkout-return'
      path: '/checkout-return'
      fullPath: '/checkout-return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trellis-test': {
      id: '/trellis-test'
      path: '/trellis-test'
      fullPath: '/trellis-test'
      preLoaderRoute: typeof TrellisTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/downloads': {
      id: '/account/downloads'
      path: '/downloads'
      fullPath: '/account/downloads'
      preLoaderRoute: typeof AccountDownloadsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountDownloadsRoute: typeof AccountDownloadsRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountDownloadsRoute: AccountDownloadsRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRoute,
  AdminQuotaRoute: AdminQuotaRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  HelpRoute: HelpRoute,
  ProjectsRoute: ProjectsRoute,
  ShareRoute: ShareRoute,
  TrellisTestRoute: TrellisTestRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
